version: '3.8'

services:
  web:
    image: simonlendev/randomdesert-localhost:linux.amd64
    build:
      context: ./django_app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./django_app/.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: